#server.port=8001
server:
  port: 8002
  servlet:
    context-path: /web-service
spring:
  application:
    name: web-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

#
#
#spring:
#  application:
#    name: HelloClient
#
#server:
#  port: 7211
#
#eureka:
#  password: password
#  client:
#    serviceUrl:
#      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    metadataMap:
#      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#
#
#endpoints:
#  restart:
#    enabled: true