server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: web-service
          uri: lb://WEB-SERVICE
          predicates:
            - Path=/web-service/**
        - id: ocpp16-hub-http-service
          uri: lb://OCPP16-HUB-SERVICE
          predicates:
            - Path=/ocpp16-hub-service/**
        - id: ocpp16-hub-websocket-service
          uri: lb:ws://OCPP16-HUB-SERVICE
          predicates:
            - Path=/ocpp16-hub-service/ocpp16/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka服务器地址
    register-with-eureka: true # 是否向Eureka注册自己，默认为true
    fetch-registry: true # 是否从Eureka获取注册信息，默认为true
    instance:
      lease-renewal-interval-in-seconds: 30 # 心跳间隔时间（秒）
      lease-expiration-duration-in-seconds: 90 # 超时时间（秒），超过该时间未收到心跳则认为服务下线
