#server.port=8001
server:
  port: 8001
  servlet:
    context-path: /ocpp16-hub-service
spring:
  application:
    name: ocpp16-hub-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
